#%RAML 1.0
title: RAML Parser Test Data
version: 0.0.1
mediaType: application/json

types:

  Foo:
    type: object
    properties:
      label: string

  Bar:
    type: object
    properties:
      comment: string

  Baz:
    type: Foo | Bar
    discriminator: true

  IdString:
    type: string
    pattern: ([a-z]|[A-Z]|[0-9]){8}
